// Shared presentational primitives, used by the builder (App.js) and the
// catalog view.
import { C } from "./theme";

export function Panel({title,children}){return (<div style={{background:C.white,borderRadius:8,padding:"18px 20px",boxShadow:"0 1px 3px rgba(0,0,0,0.05)",border:`1px solid ${C.borderLight}`}}><SecLbl>{title}</SecLbl>{children}</div>);}
export function SecLbl({children}){return (<div style={{fontSize:10.5,textTransform:"uppercase",letterSpacing:"0.12em",color:C.gold,fontWeight:700,marginBottom:12}}>{children}</div>);}
export function Lbl({children}){return (<div style={{fontSize:12,fontWeight:600,color:C.textMuted,marginBottom:5}}>{children}</div>);}
export function Stat({label,value}){return (<div><div style={{fontSize:10,color:C.textMuted,textTransform:"uppercase",letterSpacing:"0.1em",fontWeight:700,marginBottom:3}}>{label}</div><div style={{fontSize:20,fontWeight:900,color:C.navy}}>{value}</div></div>);}
export function Tog({label,checked,onChange,status}){return (<div onClick={()=>onChange(!checked)} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:14,padding:"11px 14px",borderRadius:6,cursor:"pointer",background:checked?"rgba(0,68,101,0.04)":C.white,border:`1.5px solid ${checked?C.navy:C.border}`}}><div style={{display:"flex",alignItems:"center",gap:10,flexShrink:0}}><div style={{width:38,height:20,borderRadius:10,background:checked?C.navy:"#c4cdd6",position:"relative"}}><div style={{width:16,height:16,borderRadius:8,background:C.white,position:"absolute",top:2,left:checked?20:2,transition:"left 0.2s",boxShadow:"0 1px 3px rgba(0,0,0,0.18)"}}/></div><span style={{fontSize:13.5,fontWeight:500}}>{label}</span></div>{status&&status.msg&&<span style={{fontSize:11,fontWeight:600,color:status.ok?C.success:C.danger,textAlign:"right",lineHeight:1.35,maxWidth:140,marginLeft:8}}>{status.ok?"✓":"⚠"} {status.msg}</span>}</div>);}
export function Donut({entries,colors,tw}){let cum=0;return (<div style={{position:"relative",width:180,height:180,flexShrink:0}}><svg viewBox="0 0 200 200" width="180" height="180">{entries.map(([cat,w])=>{const pct=w/tw,ang=pct*360,sa=cum;cum+=ang;const sr=(sa-90)*Math.PI/180,er=(sa+ang-90)*Math.PI/180,la=ang>180?1:0,r=82,cx=100,cy=100;if(ang<0.5)return null;const d=ang>=359.9?`M ${cx+r} ${cy} A ${r} ${r} 0 1 1 ${cx-r} ${cy} A ${r} ${r} 0 1 1 ${cx+r} ${cy}`:`M ${cx} ${cy} L ${cx+r*Math.cos(sr)} ${cy+r*Math.sin(sr)} A ${r} ${r} 0 ${la} 1 ${cx+r*Math.cos(er)} ${cy+r*Math.sin(er)} Z`;return (<path key={cat} d={d} fill={colors[cat]||"#6C757D"} stroke={C.white} strokeWidth="2.5"/>);})}<circle cx="100" cy="100" r="50" fill={C.white}/><text x="100" y="95" textAnchor="middle" style={{fontSize:24,fontWeight:900,fontFamily:"'Lato',sans-serif",fill:tw>=0.999&&tw<=1.001?C.navy:C.danger}}>{(tw*100).toFixed(0)}%</text><text x="100" y="113" textAnchor="middle" style={{fontSize:9.5,fill:C.textMuted,letterSpacing:"0.12em",fontWeight:700}}>ALLOCATED</text></svg></div>);}
